cache: bundler
language: ruby
sudo: false
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.1.6
  - 2.1.7
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - jruby-19mode
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024M --debug"
